### ISSUE TITLE
Support for HTML in answers

### ISSUE THREAD

**Issue by pkuruppu** [kjayma/surveyor_gui#39]
Hi Kevin-
Is it possible to add HTML support for answers? I've noticed that question text currently supports HTML, just not the answers.

Thanks!

**Comment by kjayma** [comment]
If Surveyor supports it, I'll support it too.

At the moment the Surveyor documentation has a section for "Doesn't Do" which includes:
"Consistently support HTML tags in title, text, help_text attributes. We intend to move to markdown support #413 so that same survey definition can be used with nu_surveyor."

Try creating a Surveyor DML file like kitchen_sink.rb.  If you can get Surveyor to show your custom HTML, I'll make sure Surveyor_gui can mirror that behavior.
