### ISSUE TITLE
Override suveyor partial inside surveyor_gui

### ISSUE THREAD

**Issue by akhildave** [kjayma/surveyor_gui#44]
First of all, Thank you for your great efforts.
I am facing difficulty to override a haml file of surveyor gem, which is originally present inside partials folder of surveyor gem. 
After including surveyor_gui, i am unable to override it. 

File Name - _question_group.html.haml 
 
![screen shot 2015-03-02 at 5 06 51 pm](https://cloud.githubusercontent.com/assets/7228028/6439980/93d99ce6-c0fe-11e4-83f2-ab6127f5c1b7.png)

File Location:

![screen shot 2015-03-02 at 5 23 20 pm](https://cloud.githubusercontent.com/assets/7228028/6440215/e4ba26f6-c100-11e4-996f-955782133d69.png)

I tried many approaches to override it and also solutions in Stack overflow. But was not able to achieve it...Can you guide in right direction...Any ideas?

Thanks

**Comment by kjayma** [comment]
I'm a little unclear as to what you are trying to do and what the problem is.  When you say you are trying to override the file, do you mean that you are trying to create a new layout that looks/works differently than the original, or are you just trying to get past the error you pasted above?

Also, can you tell me a little about your application - is this an existing application and are you trying to retrofit surveyor_gui, or is this a brand new application?

**Comment by akhildave** [comment]
@kjayma  I'm just trying to get past the error.  This is new application, using master branch of surveyor_gui.

I experienced this error when i created a question (Grid - drop-downs ) with choice for other and  comments selected.  if i exclude other and comments then it will work fine.

![screen shot 2015-03-04 at 10 16 56 am](https://cloud.githubusercontent.com/assets/7228028/6478379/b1fae13a-c257-11e4-8d93-3471d7cb0e4f.png)


Note: 
I also override question_type_methods.rb because it did not allowed me to create question when choice for other and comments are selected. It gave me error "undefined method + for nil class" because display_order of default answer was nil. Below is code snippet which i included to make it work. 

 https://gist.github.com/akhildave/786342b179a627910ecc

**Comment by kjayma** [comment]
OK, I'll take a look.  Would appreciate if you could put together a pull request for the change you did make.

**Comment by kjayma** [comment]
I tried to reproduce the error and am so far unsuccessful.  One thing I noticed is that the "Row Heading" seems to have been edited and moved to a different spot in the form.  It looks like you may have edited the _question.html.haml view.  

If this is the case, be aware that changes to the form could be affecting the operation of the javascript and ajax calls to create the new question. The problems may be caused by your code changes.  It's possible that by moving things around, the javascript may no longer pick up changes to the "Row Heading" portion of the DOM.  If you've got a fork posted to github, I could take a look and give you some more specific comments.

**Comment by akhildave** [comment]
Thanks for your response, and sorry for delayed reply, as i was away for a work.. 
Here is the complete code in github 
https://github.com/akhildave/survey-application
Skype: akhiltheway

**Comment by kjayma** [comment]
No problem.  I'll have a look as soon as I can.

**Comment by kjayma** [comment]
@akhildave I understand now how you triggered the bug, and it is indeed a problem in surveyor_gui. I'll get a fix out.

**Comment by akhildave** [comment]
Thank you
